name: Build Android APK

on:
  push:
    branches:
      - main # یا Branch مورد نظرتان
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # گام 1: کلون کردن Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # گام 2: تنظیم JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # گام 3: تنظیم Gradle Wrapper
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # گام 4: ساخت پروژه با Gradle
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # گام 5: بررسی خروجی ساخت
      - name: Check build output
        run: ls app/build/outputs/apk/debug/

      # گام 6: ذخیره فایل APK به عنوان Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: app/build/outputs/apk/debug/app-debug.apk
